[versions]
aws1 = "1.12.791"
docker = "3.6.0"
guava = "33.5.0-jre"
junit = "5.13.4"
micrometer = "1.12.13"
misk = "2025.10.31.153548-1819433"
okHttp = "5.1.0"
okio = "3.16.0"
tempest = "2025.09.18.063705-9bd8953"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.27.6" }
awsDynamodb = { module = "com.amazonaws:aws-java-sdk-dynamodb", version.ref = "aws1" }
docker = { module = "com.github.docker-java:docker-java", version.ref = "docker" }
dockerApi = { module = "com.github.docker-java:docker-java-api", version.ref = "docker" }
dockerCore = { module = "com.github.docker-java:docker-java-core", version.ref = "docker" }
dockerTransportHttpClient = { module = "com.github.docker-java:docker-java-transport-httpclient5", version.ref = "docker" }
findbugsJsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guice = { module = "com.google.inject:guice", version = "6.0.0" }
jakartaInject = { module = "jakarta.inject:jakarta.inject-api", version = "2.0.1" }
jedis = { module = "redis.clients:jedis", version = "6.2.0" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitLauncher = { module = "org.junit.platform:junit-platform-launcher" }
kotlinXHtml = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version = "0.12.0" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version = "1.5.6" }
loggingApi = { module = "io.github.microutils:kotlin-logging", version = "3.0.5" }
micrometerCore = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
misk = { module = "com.squareup.misk:misk", version.ref = "misk" }
miskActions = { module = "com.squareup.misk:misk-actions", version.ref = "misk" }
miskAdmin = { module = "com.squareup.misk:misk-admin", version.ref = "misk" }
miskApi = { module = "com.squareup.misk:misk-api", version.ref = "misk" }
miskAuditClient = { module = "com.squareup.misk:misk-audit-client", version.ref = "misk" }
miskAwsDynamodb = { module = "com.squareup.misk:misk-aws-dynamodb", version.ref = "misk" }
miskClustering = { module = "com.squareup.misk:misk-clustering", version.ref = "misk" }
miskConfig = { module = "com.squareup.misk:misk-config", version.ref = "misk" }
miskCore = { module = "com.squareup.misk:misk-core", version.ref = "misk" }
miskCron = { module = "com.squareup.misk:misk-cron", version.ref = "misk" }
miskHibernate = { module = "com.squareup.misk:misk-hibernate", version.ref = "misk" }
miskHotwire = { module = "com.squareup.misk:misk-hotwire", version.ref = "misk" }
miskInject = { module = "com.squareup.misk:misk-inject", version.ref = "misk" }
miskJdbc = { module = "com.squareup.misk:misk-jdbc", version.ref = "misk" }
miskLeaseMysql = { module = "com.squareup.misk:misk-lease-mysql", version.ref = "misk" }
miskLogging = { module = "com.squareup.misk:misk-logging", version.ref = "misk" }
miskPrometheus = { module = "com.squareup.misk:misk-prometheus", version.ref = "misk" }
miskRateLimitingBucket4jDynamodbV1 = { module = "com.squareup.misk:misk-rate-limiting-bucket4j-dynamodb-v1", version.ref = "misk" }
miskRateLimitingBucket4jMysql = { module = "com.squareup.misk:misk-rate-limiting-bucket4j-mysql", version.ref = "misk" }
miskRateLimitingBucket4jRedis = { module = "com.squareup.misk:misk-rate-limiting-bucket4j-redis", version.ref = "misk" }
miskRedis = { module = "com.squareup.misk:misk-redis", version.ref = "misk" }
miskService = { module = "com.squareup.misk:misk-service", version.ref = "misk" }
miskTailwind = { module = "com.squareup.misk:misk-tailwind", version.ref = "misk" }
miskTesting = { module = "com.squareup.misk:misk-testing", version.ref = "misk" }
miskTokens = { module = "com.squareup.misk:misk-tokens", version.ref = "misk" }
miskVitess = { module = "com.squareup.misk:misk-vitess", version.ref = "misk" }
moshiCore = { module = "com.squareup.moshi:moshi", version = "1.15.2" }
mysql = { module = "com.mysql:mysql-connector-j", version = "8.4.0" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttpMockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
slf4jApi = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
tempest2TestingDocker = { module = "app.cash.tempest:tempest2-testing-docker", version.ref = "tempest" }
tempest2TestingJvm = { module = "app.cash.tempest:tempest2-testing-jvm", version.ref = "tempest" }
wispDeployment = { module = "app.cash.wisp:wisp-deployment", version.ref = "misk" }
wispLease = { module = "app.cash.wisp:wisp-lease", version.ref = "misk" }
wispLoggingTesting = { module = "app.cash.wisp:wisp-logging-testing", version.ref = "misk" }
wispRateLimiting = { module = "app.cash.wisp:wisp-rate-limiting", version.ref = "misk" }
wispToken = { module = "app.cash.wisp:wisp-token", version.ref = "misk" }
